name: rlsnake
services:
    rlsnake:
        # devices:
        #     - nvidia.com/gpu=all
        volumes:
        - type: bind
          source: ./lib
          target: /workspace/lib
        - type: bind
          source: ./training
          target: /workspace/training
        env_file: .env
        stdin_open: true
        tty: true
        image: rlsnake
